apps/course/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import CourseListView, CourseRecommendView, VideoPlayView, CourseDetailView, CourseInfoView, CourseCommentView, AddCommentView

app_name = 'course'

urlpatterns = [
    url(r'list/', CourseListView.as_view(), name='course_list'),

    url(r'recommend/', CourseRecommendView.as_view(), name='course_recommend'),

    # 课程详情页
    url('detail/(?P<course_id>\d+)/', CourseDetailView.as_view(), name="course_detail"),

    #课程信息页
    url('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name="course_info"),

    # 课程评论页
    url('comment/(?P<course_id>\d+)/', CourseCommentView.as_view(), name="course_comment"),

    # 添加课程评论
    url('add_comment/', AddCommentView.as_view(), name="add_comment"),

    # 课程视频
    url('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name="video_play"),

]

apps/organization/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

# from .views import OrgView, UserAskView, OrgHomeView, OrgCourseView, OrgTeacherView, OrgDescView
from .views import *


app_name = "organization"

urlpatterns = [

    # 课程机构列表
    url(r'^list/$', OrgView.as_view(), name="org_list"),

    # 用户咨询表单
    url(r'^add_ask/$', UserAskView.as_view(), name="add_ask"),

    # 机构首页
    url(r'home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name="org_home"),

    # 课程机构列表
    url(r'course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name="org_course"),

    # 机构讲师页
    url(r'teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name="org_teacher"),

    # 机构详情页
    url(r'desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name="org_desc"),

    # 收藏，取消收藏
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),

    # 所有教师列表
    url(r'teacher/list/$', TeacherListView.as_view(), name="teacher_list"),

    # 讲师详情页
    url(r'teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail"),
]

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import MyFavView, MyMessageView, MyCourseView, UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView

app_name = "users"

urlpatterns = [

    # 用户信息
    url(r"^info/$", UserInfoView.as_view(), name="user_info"),

    # 用户修改头像
    url(r"^image/upload/$", UploadImageView.as_view(), name="image_upload"),

    # 更新密码
    url(r"^update/pwd/$", UpdatePwdView.as_view(), name="update_pwd"),

    # 发送验证码
    url(r"^sendemail_code/$", SendEmailCodeView.as_view(), name="sendemail_code"),

    # 修改邮箱
    url(r"update_email/$", UpdateEmailView.as_view(), name="update_email"),

    # 用户课程
    url(r"^mycourse/$", MyCourseView.as_view(), name="my_course"),

    # 用户收藏
    url(r"^my_fav/$", MyFavView.as_view(), name="my_fav"),

    # 用户消息
    url(r"^mymessage/$", MyMessageView.as_view(), name="my_message"),
]

extra_apps/DjangoUeditor3-master/DUSite/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
import settings
from django.contrib import admin
from TestApp.views import  TestUEditorModel,ajaxcmd,TestUEditor

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^test/$',TestUEditorModel),
    url(r'^test2/$',TestUEditor),
    url(r'^ajaxcmd/$',ajaxcmd)

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
        url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
        url(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    )

extra_apps/DjangoUeditor3-master/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/course/models.py
from datetime import datetime

from django.db import models
# from DjangoUeditor.models import UEditorField

from organization.models import CourseOrg, Teacher


# Create your models here.


class Course(models.Model):
    """课程"""
    DEGREE_CHOICE = (
        ('cj', 'Junior'),
        ('zj', 'Middle'),
        ('gj', 'Senior'),
    )
    course_org = models.ForeignKey(CourseOrg, verbose_name="Organization", on_delete=models.CASCADE, null=True, blank=True)
    teacher = models.ForeignKey(Teacher, verbose_name="Teacher", on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u"Course name")
    desc = models.CharField(max_length=300, verbose_name=u"Description")
    detail = models.TextField(verbose_name=u"Detail")
    # detail = UEditorField(verbose_name='内容	', width=600, height=300, toolbars="full", imagePath="course/image/", filePath="course/image/", upload_settings={"imageMaxSize":1204000},
    #          settings={}, command=None, blank=True)
    degree = models.CharField(verbose_name=u"Difficulty", choices=DEGREE_CHOICE, max_length=100)
    learn_times = models.IntegerField(default=0, verbose_name=u"Time cost(min)")
    students = models.IntegerField(default=0, verbose_name=u"Learner")
    fav_nums = models.IntegerField(default=0, verbose_name=u"Collected")
    image = models.ImageField(upload_to="course/%Y/%m", verbose_name=u"Cover Image", max_length=100, blank=True)
    click_nums = models.IntegerField(default=0, verbose_name=u"Clicks")
    category = models.CharField(max_length=30, default="Type", verbose_name="Type")
    tag = models.CharField(max_length=300, default="", verbose_name="tags")
    need_know = models.CharField(max_length=300, default="", verbose_name="Course Notice")
    teacher_tell = models.CharField(max_length=300, default="", verbose_name="Teacher tell you")
    is_banner = models.BooleanField('Rotating broadcast', default=False)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"Add time")

    class Meta:
        # verbose_name = u"课程"
        verbose_name = u"Courses"
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取章节数
        return self.lesson_set.all().count()
    # xadmin后台课程列表页显示章节数函数的名称
    get_zj_nums.short_description = "Chapters"

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe('<a href="http://www.baidu.com">Link</a>')
    go_to.short_description = "Link"

    def get_learn_users(self):
        # 获取当前课程5个的学习用户
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        # 获取当前课程所有的章节
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class BannerCourse(Course):
    """显示轮播课程"""
    class Meta:
        # verbose_name = '轮播课程'
        verbose_name = 'Rotating courses'
        verbose_name_plural = verbose_name
        # 单例 这里必须设置proxy=True，这样就不会在生成一张表，而且具有Model的功能
        proxy = True


class Lesson(models.Model):
    """课程章节"""

    course = models.ForeignKey(Course, verbose_name=u"course", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"chapter name")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"add time")

    class Meta:
        # verbose_name = u"章节"
        verbose_name = u"Chapter"
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        # 获取当前章节的所有相关学习视频
        return self.video_set.all()

    def __str__(self):
        return '《{0}》Chapters >> {1}'.format(self.course, self.name)


class Video(models.Model):
    """章节学习视频"""

    lesson = models.ForeignKey(Lesson, verbose_name=u"chapter", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"video name")
    learn_times = models.IntegerField(verbose_name="duration(mins)", default=20)
    url = models.CharField(verbose_name="chapter video", default="", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"add time")

    class Meta:
        # verbose_name = u"视频"
        verbose_name = u"Video"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    """课程学习资源"""

    course = models.ForeignKey(Course, verbose_name=u"chapter", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"name")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"resouce file", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"add time")

    class Meta:
        # verbose_name = u"课程资源"
        verbose_name = u"Course Resource"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name





apps/users/forms.py
# -*- coding: utf-8 -*-
import re

from django import forms
from captcha.fields import CaptchaField  # 验证码字段

from .models import UserProfile


# 前端进行简单表单验证之后，为了避免刻意的网络攻击，后台仍需验证
# 另外对表单进行验证，减少与数据库交互，减轻负担
class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={"invalid": "code wrong"})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={"invalid": "code wrong"})


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=6, max_length=20, error_messages={"required": "不可为空"})
    password2 = forms.CharField(required=True, min_length=6, max_length=20, error_messages={"required": "不可为空"})


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["image"]


class UserInfoForm(forms.ModelForm):
    """
    用户信息修改
    """
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'address' , 'birthday', 'mobile', 'gender', 'tags']

    def clean_mobile(self):
        """
        验证手机号是否合法. 定义函数必须以clean_开头
        """
        mobile = self.cleaned_data['mobile']
        regex_mobile = r'^1[358]\d{9}$|^147\d{8}$|176\d{8}$'
        pattern_mobile = re.compile(regex_mobile)
        if pattern_mobile.match(mobile):
            return mobile
        else:
            raise forms.ValidationError("手机号非法", code="invalid mobile")

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}Online Education{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}{% endblock custom_css %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>

<section class="headerwrap ">
    <header>
		<div  class=" header">
            <div class="top">
                <div class="wp">
                    <div  class="fl"><p><a style="color: white;font-size: 18px;" href="###"><b>Online Education</b></a></p></div>

                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static "images/top_down.png" %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class=" userdetail ">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                    <dd>
                                        <h2>{{ request.user.nick_name }}</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">User Center</a>
                                    <a class="fr" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <!-- <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Register</a> -->
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </div>


            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                               Open Class
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">Open Class</li>
                                <li data-value="org">Organization</li>
                                <li data-value="teacher">Teachers</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="Input search"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
{#                    使用切片的得到的路径与request相对路径进行匹配#}
						<ul>
                            <li {% if request.path == '/' %}class="active" {% endif %}><a
                                    href="{% url 'index' %}">Index</a></li>
                            <li {% if request.path|slice:'12' == '/course/list' %}class="active"{% endif %}>
                                <a href="{% url 'course:course_list' %}">
                                  Open Class
                                </a>
                            </li>

                            <li {% if request.path|slice:'17' == '/course/recommend' %}class="active"{% endif %}>
                              <a href="{% url 'course:course_recommend' %}">
                                  Recommend<img class="hot" src="{% static 'images/nav_hot.png' %}">
                              </a>
                            </li>

                            <li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
                                <a href="{% url 'org:teacher_list' %}">Teachers</a>
                            </li>
                            <li {% if request.path|slice:'9' == '/org/list' %}class="active" {% endif %}><a
                                    href="{% url 'org:org_list' %}">Organization</a></li>
                        </ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">Index</a>></li>
            </ul>
        </div>
    </section>
{% endblock custom_bread %}

{% block custom_content %}
{% endblock custom_content %}

<footer>
		<div class="footer">
			<div class="wp">
                <!--
				<ul class="cont">
					<li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/hpuwx.png' %}"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">3987XXX</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>
                -->
			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">Online Education</span>
                <span class="fr"></span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="totop"></li>
    </ul>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
{#全局搜索#}
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
{% block custom_js %}{% endblock custom_js %}
</body>
</html>

templates/forgetpwd.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>Online Education</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div class="resetpassbox dialogbox" id="jsSetNewPwd">
    <h1>重新设置密码</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <p class="green">请输入新密码</p>
    <form id="jsSetNewPwdForm">
        {% csrf_token %}
        <div class="box">
            <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
            <input type="password" name="password" id="jsResetPwd" placeholder="请输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">确&nbsp;认&nbsp;密&nbsp;码</span>
            <input type="password" name="password2" id="jsResetPwd2" placeholder="请再次输入新密码"/>
        </div>
        <div class="box">
            <span class="word2">验&nbsp;&nbsp;证&nbsp;&nbsp;码</span>
            <input type="text" name="code" id="jsResetCode" placeholder="请输入手机验证码"/>
        </div>
        <div class="error btns" id="jsSetNewPwdTips"></div>
        <div class="button">
            <input type="hidden" name="mobile" id="jsInpResetMobil" />
            <input id="jsSetNewPwdBtn" type="button" value="提交" />
        </div>
    </form>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">Online Education</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li><a href="{% url 'login' %}">[登录]</a></li>
                <li class="active"><a href="{% url 'forget_pwd' %}">[忘记密码]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'index' %}"></a>
                <a class="index-font" href="{% url 'index' %}">Index</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/lab01.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/lab02.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>忘记密码</h2>
                <form id="jsFindPwdForm" method="post" action="{% url 'forget_pwd' %}" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group marb20 {% if forget_from.errors.email %}errorput{% endif %}">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="{{ forget_from.email.value }}" placeholder="邮箱" />
                    </div>
                    <div class="form-group captcha1 marb38 {% if forget_from.errors.captcha %}errorput{% endif %}">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ forget_from.captcha }}
                    </div>
                    <div class="error btns" id="jsForgetTips">
                        {% for key, value in forget_from.errors.items %}
                            {{ value }}
                        {% endfor %}
                        {{ msg }}
                    </div>
                    <input type="hidden" name="sms_type" value="1">
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                    <p class="form-p" style="bottom:40px;">您还可以<a href="{% url 'login' %}"> [直接登录]</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Online Education{% endblock title %}

{% block custom_bread %}{% endblock custom_bread %}

{% block custom_content %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            <!--{% for banner in all_banners %}
                            <li>
                                <a href="http://www.cnblogs.com/welan/">
                                    <img width="1200" height="460" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                </a>
                            </li>
                            {% endfor %}-->
							<li><a href=""><img width="1200" height="400" src="{% static 'images/news1.png' %}" /></a></li>
							<li><a href=""><img width="1200" height="400" src="{% static 'images/news2.png' %}" /></a></li>
							<li><a href=""><img width="1200" height="400" src="{% static 'images/news3.png' %}" /></a></li>
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature1.png' %}"/>
					<p class="center">Professional authority</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature2.png' %}"/>
					<p class="center">Latest courses</p>
				</li>
				<li class="feature3">
					<img class="pic" src="{% static 'images/feature3.png' %}"/>
					<p class="center">Renowned teachers</p>
				</li>
				<li class="feature4">
                    <a href="http://8.134.112.5:33891/tree">
                       <img class="pic" src="{% static 'images/feature4.png' %}"/>
                    </a>
					<p class="center">Experimental platform</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>Open Class</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
						<p class="fisrt_word">Renowned teachers<br/>Professional authority</p>
						<a class="more" href="{% url 'course:course_list' %}">more... ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    <!--{% for banner_course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course:course_detail' banner_course.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" alt="{{ banner_course.tag }}" />
                                        </a>
                                    </li>
                                    {% endfor %}-->
									<li><a href=""><img width="470" height="300" src="{% static 'images/course_f1.png' %}" /></a></li>
                                    <li><a href=""><img width="470" height="300" src="{% static 'images/course_f2.png' %}" /></a></li>
                                    <li><a href=""><img width="470" height="300" src="{% static 'images/course_f3.png' %}" /></a></li>
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                        {% for course in courses %}
                        <div class="module1_{{ forloop.counter|add:2 }} box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                </a>
                                <span class="fl">Difficulty：<i class="key">{{ course.get_degree_display }}</i></span>
                                <span class="fr">Learners：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                <span class="star fr">{{ course.course_org.fav_nums }}</span>
                            </div>
                        </div>
                        {% endfor %}
                            
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="300" src="{% static 'images/module3_1.jpg' %}"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                                {% for org in course_orgs %}
                                 <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
{#                                 能够被5整除#}
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                                {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	-->
{% endblock custom_content %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock custom_js %}